// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdxP_YSzEgPXBRBzDt1KLiryTTp3iD90k',
    appId: '1:159729368663:web:31437f635494ab5a1a2d12',
    messagingSenderId: '159729368663',
    projectId: 'see-for-me-6958d',
    authDomain: 'see-for-me-6958d.firebaseapp.com',
    storageBucket: 'see-for-me-6958d.firebasestorage.app',
    measurementId: 'G-YPGK5P771P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRIZA0qL4ltpo_Sjb402S_o-iaZqDy4Ac',
    appId: '1:159729368663:android:a3dea1d14a003f391a2d12',
    messagingSenderId: '159729368663',
    projectId: 'see-for-me-6958d',
    storageBucket: 'see-for-me-6958d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFHhguG8kLv_NLq2Z5Y_7DzXr-bO9dDlI',
    appId: '1:159729368663:ios:8bea2f42002b06c21a2d12',
    messagingSenderId: '159729368663',
    projectId: 'see-for-me-6958d',
    storageBucket: 'see-for-me-6958d.firebasestorage.app',
    iosClientId: '159729368663-4et40athlarlhjt892hc7ibjenm8u5ha.apps.googleusercontent.com',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFHhguG8kLv_NLq2Z5Y_7DzXr-bO9dDlI',
    appId: '1:159729368663:ios:8bea2f42002b06c21a2d12',
    messagingSenderId: '159729368663',
    projectId: 'see-for-me-6958d',
    storageBucket: 'see-for-me-6958d.firebasestorage.app',
    iosClientId: '159729368663-4et40athlarlhjt892hc7ibjenm8u5ha.apps.googleusercontent.com',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdxP_YSzEgPXBRBzDt1KLiryTTp3iD90k',
    appId: '1:159729368663:web:8c2435609e204de11a2d12',
    messagingSenderId: '159729368663',
    projectId: 'see-for-me-6958d',
    authDomain: 'see-for-me-6958d.firebaseapp.com',
    storageBucket: 'see-for-me-6958d.firebasestorage.app',
    measurementId: 'G-G5ER4LEDJW',
  );
}
